name: Deploy Containers
on:
  push:
    branches:
      - main
      - deploy-action
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the Docker directory
            cd $HOME/Docker/dso-conduit

            # Update the repository
            git pull origin main

            # Build and run the containers
            docker compose up -d --build --remove-orphans